** Abstract


The repository collects the /sources/ of the ``Smile'' project, in the
software programming lab course ``programming-in-the-many'', winter 2006/07
at the University Kiel.

For the webpages of the course, see [[http://heim.ifi.uio.no/msteffen/teaching/softtech/ws0607/pitm-uml][here]].


** Structure


    - [[,/Readme.org]]:        this file
    - [[./org]]:               course related information, including a file  [[./org/Readme-course.txt]] 
                           describing the (initial) structure of the code.
                           development steps
    - [[./dokumentation/]]     information and documentation
    - [[./src/]]               the sources


** Historical notes

The repository has been resurrected by migrating from ~cvs~ via svn (using
~cvs2svn~) and from there to ~git~. Caveats concerning missing branches
apply. 

In this particular repos, it indeed seems that the transfer *missed* later
revisions. The reasons is unclear, probably, the svn-dump was not done at
the end of the project, but only at an intermediate state (and I did not
find the CVS). Anyway, I updated then the files with the /latest/ version I
found, meaning that there is a ``gap'' in the respository.




