/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package csm.expression.parser;

public interface ExpressionParserConstants {

  int EOF = 0;
  int LPAREN = 5;
  int COMMA = 6;
  int RPAREN = 7;
  int SKIP_ = 8;
  int SEND = 9;
  int RANDOM = 10;
  int ASSIGN = 11;
  int OR = 12;
  int AND = 13;
  int NOT = 14;
  int EQ = 15;
  int NEQ = 16;
  int GEQ = 17;
  int LEQ = 18;
  int GT = 19;
  int LT = 20;
  int PLUS = 21;
  int MINUS = 22;
  int MUL = 23;
  int TRUE = 24;
  int FALSE = 25;
  int WLA = 26;
  int NAB = 27;
  int INTNUM = 28;
  int IDENT = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"skip\"",
    "\"send\"",
    "\"random\"",
    "\":=\"",
    "\"|\"",
    "\"&\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"true\"",
    "\"false\"",
    "\"wla\"",
    "\"nab\"",
    "<INTNUM>",
    "<IDENT>",
  };

}
